### ISSUE TITLE
Enable specifying machine tags for CAPI-MAAS infrastructure cluster template

### ISSUE THREAD

**Issue by vishvikkrishnan** [canonical/cluster-api-bootstrap-provider-microk8s#88]
The cluster template for MAAS does not allow specifying machine tags to target a node for the cluster deployment; currently it is only possible to specify the [resource pool](https://github.com/canonical/cluster-api-bootstrap-provider-microk8s/blob/main/templates/cluster-template-maas.yaml#L56). However, this feature is already available on the infra provider - ref: https://github.com/spectrocloud/cluster-api-provider-maas/commit/bb8204bf85b45495811bd7dcd9a4ee48f3ce7fd7

The cluster template and .rc files for MAAS need to allow specifying machine tags for the control-plane and worker machines. Example for worker machine tag:

cluster-template-maas.rc:
```shell
export WORKER_MACHINE_TAGS="cloud,compute"
```

cluster-template-maas.yaml:
```yaml
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: MaasMachineTemplate
metadata:
  name: microk8s-maas-md-0
  namespace: default
spec:
  template:
    spec:
      image: ubuntu/jammy
      minCPU: 1
      minMemory: 2048
      resourcePool: bare-metal-pool
      tags:
      - cloud
      - compute
```
